# Generated by Django 3.2.7 on 2021-09-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='wholeTxt',
            field=models.FileField(upload_to='media/files/%Y/%m/%d/', verbose_name='Загрузите файл'),
        ),
    ]
